services:
  self-ip:
    container_name: self-ip
    image: ghcr.io/sintan1729/self-ip:latest
    restart: on-failure:5
    ports:
      - "3213:3213" # Adjust if needed

    environment:
      # CHANGE IT BEFORE DEPLOYMENT, THIS IS GIBBERISH
      # Make sure that you replace $ with $$ before putting the digest here
      SELF_IP_API_KEY: "$$argon2id$$v=19$$m=16,t=2,p=2$$c3F3ZGFkdsdedadaddasdadscaafhjasajsnjasbfjfas"
      # SELF_IP_TRUSTED_PROXIES: 10.89.0.0/24
      # SELF_IP_LISTEN_ADDR: 0.0.0.0
      # SELF_IP_LISTEN_PORT: 1122
      TZ: Asia/Kolkata
    healthcheck:
      test: CMD-SHELL wget -qO- http://127.0.0.1:1729/healthz || exit 1
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 10s

    volumes:
      - self-ip:/app/maxmind-databases

volumes:
  self-ip:
