# Build stage
FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o self-ip .
ARG GIT_VERSION=""

RUN if [ -n "$GIT_VERSION" ]; then \
      CGO_ENABLED=0 GOOS=linux go build \
        -ldflags="-s -w -X main.Version=$GIT_VERSION" \
        -o self-ip; \
    else \
      CGO_ENABLED=0 GOOS=linux go build \
        -ldflags="-s -w" \
        -o self-ip; \
    fi

# Release container
FROM alpine:latest
RUN apk add --no-cache tzdata

WORKDIR /app
COPY --from=builder /app/self-ip /app/self-ip

EXPOSE 3213
CMD ["/app/self-ip"]
